# Auto-generated by server-start.ps1 - do not edit manually
$ProjectRoot = 'C:\Users\USER\Desktop\rpt_monitor\rpt_monitor'
$LogOut      = 'C:\Users\USER\Desktop\rpt_monitor\rpt_monitor\logs\server-out.log'
$LogErr      = 'C:\Users\USER\Desktop\rpt_monitor\rpt_monitor\logs\server-err.log'
$PidFile     = 'C:\Users\USER\Desktop\rpt_monitor\rpt_monitor\.server.pid'
$MaxRestarts = 10
$restarts    = 0

while ($restarts -lt $MaxRestarts) {
    Write-Host "[$(Get-Date -f 'HH:mm:ss')] Starting server (attempt $($restarts+1))..." 
    
    $proc = Start-Process `
        -FilePath 'npx.cmd' `
        -ArgumentList 'tsx', '.\server.ts' `
        -WorkingDirectory $ProjectRoot `
        -RedirectStandardOutput $LogOut `
        -RedirectStandardError $LogErr `
        -PassThru `
        -WindowStyle Hidden
    
    $proc.Id | Set-Content $PidFile
    Write-Host "[$(Get-Date -f 'HH:mm:ss')] Server PID $($proc.Id) started"
    
    $proc.WaitForExit()
    $exitCode = $proc.ExitCode
    
    if ($exitCode -eq 0) {
        Write-Host "[$(Get-Date -f 'HH:mm:ss')] Server exited cleanly (code 0). Stopping."
        break
    }
    
    $restarts++
    Write-Host "[$(Get-Date -f 'HH:mm:ss')] Server crashed (code $exitCode). Restart $restarts/$MaxRestarts in 5s..."
    Start-Sleep -Seconds 5
}

if ($restarts -ge $MaxRestarts) {
    Write-Host "[$(Get-Date -f 'HH:mm:ss')] Max restarts reached. Check $LogErr for errors."
}
Remove-Item $PidFile -Force -ErrorAction SilentlyContinue
