# ==============================================================
# RPT Monitor - Start Server (Windows, no PM2 needed)
# Runs tsx server.ts in a hidden window with auto-restart.
# Logs go to .\logs\
# ==============================================================

param(
    [switch]$WithNginx,
    [switch]$Verbose
)

$ProjectRoot = $PSScriptRoot
$LogDir = "$ProjectRoot\logs"
$PidFile = "$ProjectRoot\.server.pid"
$LogOut = "$LogDir\server-out.log"
$LogErr = "$LogDir\server-err.log"
$WatcherScript = "$ProjectRoot\.server-watcher.ps1"

# Ensure logs directory exists
New-Item -ItemType Directory -Path $LogDir -Force | Out-Null

# ── Kill any existing server ──────────────────────────────────
if (Test-Path $PidFile) {
    $oldPid = (Get-Content $PidFile -ErrorAction SilentlyContinue).Trim()
    if ($oldPid -match '^\d+$') {
        Write-Host "Stopping previous server (PID $oldPid)..." -ForegroundColor Yellow
        Stop-Process -Id ([int]$oldPid) -Force -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 1
    }
    Remove-Item $PidFile -Force -ErrorAction SilentlyContinue
}

# Kill anything on port 3000
$listening = netstat -ano 2>$null | Select-String ":3000 " | Select-String "LISTENING"
if ($listening) {
    $rows = @($listening)
    foreach ($row in $rows) {
        $parts = $row.ToString() -split '\s+'
        $pidNum = $parts | Where-Object { $_ -match '^\d+$' } | Select-Object -Last 1
        if ($pidNum) {
            taskkill /PID $pidNum /F 2>$null | Out-Null
            Write-Host "Freed port 3000 (killed PID $pidNum)" -ForegroundColor Yellow
        }
    }
    Start-Sleep -Seconds 1
}

# ── Write watcher script (restarts server on crash) ──────────
$watcherContent = @"
# Auto-generated by server-start.ps1 - do not edit manually
`$ProjectRoot = '$($ProjectRoot -replace "'", "''")'
`$LogOut      = '$($LogOut -replace "'", "''")'
`$LogErr      = '$($LogErr -replace "'", "''")'
`$PidFile     = '$($PidFile -replace "'", "''")'
`$MaxRestarts = 10
`$restarts    = 0

while (`$restarts -lt `$MaxRestarts) {
    Write-Host "[`$(Get-Date -f 'HH:mm:ss')] Starting server (attempt `$(`$restarts+1))..." 
    
    `$proc = Start-Process ``
        -FilePath 'npx.cmd' ``
        -ArgumentList 'tsx', '.\server.ts' ``
        -WorkingDirectory `$ProjectRoot ``
        -RedirectStandardOutput `$LogOut ``
        -RedirectStandardError `$LogErr ``
        -PassThru ``
        -WindowStyle Hidden
    
    `$proc.Id | Set-Content `$PidFile
    Write-Host "[`$(Get-Date -f 'HH:mm:ss')] Server PID `$(`$proc.Id) started"
    
    `$proc.WaitForExit()
    `$exitCode = `$proc.ExitCode
    
    if (`$exitCode -eq 0) {
        Write-Host "[`$(Get-Date -f 'HH:mm:ss')] Server exited cleanly (code 0). Stopping."
        break
    }
    
    `$restarts++
    Write-Host "[`$(Get-Date -f 'HH:mm:ss')] Server crashed (code `$exitCode). Restart `$restarts/`$MaxRestarts in 5s..."
    Start-Sleep -Seconds 5
}

if (`$restarts -ge `$MaxRestarts) {
    Write-Host "[`$(Get-Date -f 'HH:mm:ss')] Max restarts reached. Check `$LogErr for errors."
}
Remove-Item `$PidFile -Force -ErrorAction SilentlyContinue
"@

Set-Content -Path $WatcherScript -Value $watcherContent -Encoding UTF8

# ── Launch watcher in a hidden window ────────────────────────
Write-Host ""
Write-Host "Starting RPT Monitor server..." -ForegroundColor Cyan
Write-Host "  Logs (stdout): $LogOut" -ForegroundColor DarkGray
Write-Host "  Logs (errors): $LogErr" -ForegroundColor DarkGray

$watcherProc = Start-Process `
    -FilePath "powershell.exe" `
    -ArgumentList "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", "$WatcherScript" `
    -WindowStyle Hidden `
    -PassThru

Write-Host "  Watcher PID: $($watcherProc.Id)" -ForegroundColor DarkGray
Write-Host ""

# Wait for server to spin up
Write-Host "Waiting for server to start..." -ForegroundColor Yellow
$started = $false
for ($i = 0; $i -lt 20; $i++) {
    Start-Sleep -Seconds 1
    $check = netstat -ano 2>$null | Select-String ":3000 " | Select-String "LISTENING"
    if ($check) {
        $started = $true
        break
    }
    Write-Host "  [$i/20] Waiting..." -ForegroundColor DarkGray
}

if ($started) {
    # Read back the server PID if written
    $serverPid = if (Test-Path $PidFile) { (Get-Content $PidFile).Trim() } else { "?" }
    Write-Host "  ✓ Server is listening on port 3000! (PID $serverPid)" -ForegroundColor Green
}
else {
    Write-Host "  ! Server not yet listening. Check logs:" -ForegroundColor DarkYellow
    Write-Host "    Get-Content '$LogErr' -Tail 20" -ForegroundColor DarkGray
}

# ── Nginx setup ───────────────────────────────────────────────
if ($WithNginx) {
    Write-Host ""
    Write-Host "Setting up Nginx..." -ForegroundColor Cyan
    & "$ProjectRoot\nginx-start.ps1"
}

# ── Tailscale ─────────────────────────────────────────────────
Write-Host ""
$tsIp = (tailscale ip -4 2>$null)
if ($tsIp) {
    $tsIp = $tsIp.Trim()
    Write-Host "  ✓ Tailscale IP: $tsIp" -ForegroundColor Green
    Write-Host "  → Access from Tailscale: http://$tsIp`:3000" -ForegroundColor Cyan
    
    # Update ALLOWED_ORIGINS in .env
    $envContent = Get-Content "$ProjectRoot\.env" -Raw
    $newOrigins = "http://localhost:3000,http://127.0.0.1:3000,http://${tsIp}:3000,http://${tsIp}"
    $envContent = $envContent -replace "ALLOWED_ORIGINS=.*", "ALLOWED_ORIGINS=$newOrigins"
    Set-Content "$ProjectRoot\.env" $envContent -Encoding UTF8
    Write-Host "  ✓ ALLOWED_ORIGINS updated in .env" -ForegroundColor Green
}
else {
    Write-Host "  i Tailscale not detected (optional)" -ForegroundColor DarkGray
}

# ── Summary ───────────────────────────────────────────────────
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "  RPT Monitor is running!" -ForegroundColor Green
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "  http://localhost:3000" -ForegroundColor Cyan
if ($tsIp) { Write-Host "  http://${tsIp}:3000" -ForegroundColor Cyan }
Write-Host ""
Write-Host "  Manage:" -ForegroundColor White
Write-Host "  Stop server  : .\server-stop.ps1" -ForegroundColor DarkGray
Write-Host "  View logs    : Get-Content .\logs\server-out.log -Tail 50 -Wait" -ForegroundColor DarkGray
Write-Host "  View errors  : Get-Content .\logs\server-err.log -Tail 50 -Wait" -ForegroundColor DarkGray
Write-Host ""
